#ifndef InotifyException_h
#define InotifyException_h

#include <stdexcept>

/** Class of any exception generated by the Inotify_cpp library */
class InotifyException : public std::runtime_error {
	public:
		/** Standard constructor specifying an error message
			@param m A message describing the exception
		*/
		InotifyException(std::string m) : std::runtime_error(m) { }
		
};

#endif
